pull_request_rules:
  - name: Automatic merge
    conditions:
      - label!=no-mergify
      - "#approved-reviews-by>=1"
      - status-success=continuous-integration/appveyor/pr
      - status-success=big-endian-test
      - status-success=msrv-check
      - status-success=build (stable)
      - status-success=clippy-rustfmt
      - status-success=code_gen
    actions:
      merge:
        method: merge
      delete_head_branch: {}
      dismiss_reviews: {}
