pull_request_rules:
  - name: Automatic merge
    conditions:
      - label!=no-mergify
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
      delete_head_branch: {}
      dismiss_reviews: {}
