language: rust
dist: bionic # x11rb needs at least libxcb 1.12
rust:
  # std::io::IoSlice was stabilised in 1.36.0, but 1.36.0 fails with a weird
  # error enabled by deny(single_use_lifetimes).
  - 1.37.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - xvfb

install:
  # Run the examples as 'integration tests'. For this, there is a special
  # timeout mode where the examples close automatically after some time.
  - |
    run_examples() {
        for example in examples/*.rs; do
            example=${example/examples\//}
            example=${example/.rs/}
            if [ "$example" != tutorial ] ; then
                X11RB_EXAMPLE_TIMEOUT=1 xvfb-run -a cargo run --example "$example" "$@" || exit 1
            fi
        done
    }

script:
  # Check the code generator. Output should be identical to the
  # commited version.
  - make
  - if ! git diff --exit-code; then exit 1; fi

  - |
    if [ "x$TRAVIS_RUST_VERSION" != "x1.37.0" ]; then
        rustup component add clippy
        cargo clippy -p x11rb-generator --all-targets -- -D warnings || return 1
        cargo clippy --all-targets --all-features -- -D warnings || return 1
    fi

  - |
    if [ "x$TRAVIS_RUST_VERSION" != "x1.37.0" ]; then
        rustup component add rustfmt
        cargo fmt --all -- --check || exit 1
    fi

  - cargo build --verbose --all-targets --all-features
  - cargo test --verbose --all-features
  - cargo doc --verbose --all-features

  # Run the examples as 'integration tests'.
  # Enable the 'all-extensions' feature or Cargo will complain
  - run_examples --features all-extensions

  - cargo build --verbose --all-targets --no-default-features --features all-extensions

  # Run the examples as 'integration tests'. This time using RustConnection.
  - run_examples --no-default-features --features "all-extensions libc"
