[package]
name = "x11rb"
version = "0.1.0"
authors = ["Uli Schlachter <psychon@znc.in>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
