name: CI

on:
  push:
  pull_request:
  schedule:
    # Midnight on the 1st of a month
    - cron: '0 0 1 * *'

env:
  CARGO_TERM_COLOR: always
  MOST_FEATURES: all-extensions cursor image

jobs:
  code_gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Clear src/protocol directories in x11rb and x11rb-protocol
      run: rm -rf x11rb/src/protocol/ x11rb-protocol/src/protocol/
    - name: Run code generator
      run: make
    - name: Check for changes
      run: if ! git diff --exit-code; then exit 1; fi

  clippy-rustfmt:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         include:
           - rust: stable
           - rust: beta
     steps:
       - uses: actions/checkout@v2
       - name: Install rustfmt and clippy
         uses: actions-rs/toolchain@v1
         with:
           profile: minimal
           toolchain: ${{ matrix.rust }}
           override: true
           components: rustfmt, clippy

       # rustfmt
       - name: rustfmt
         uses: actions-rs/cargo@v1
         with:
           command: fmt
           args: --all -- --check

       # clippy
       - name: clippy x11rb without features
         uses: actions-rs/cargo@v1
         with:
           command: clippy
           args: -p x11rb --all-targets -- -D warnings ${{ matrix.clippy_args }}

       - name: clippy x11rb with allow-unsafe-code but without dl-libxcb
         uses: actions-rs/cargo@v1
         with:
           command: clippy
           args: -p x11rb --all-targets --features "allow-unsafe-code" -- -D warnings ${{ matrix.clippy_args }}

       - name: clippy x11rb with allow-unsafe-code and dl-libxcb
         uses: actions-rs/cargo@v1
         with:
           command: clippy
           args: -p x11rb --all-targets --features "allow-unsafe-code dl-libxcb" -- -D warnings ${{ matrix.clippy_args }}

       - name: clippy workspace with all features
         uses: actions-rs/cargo@v1
         with:
           command: clippy
           args: --workspace --all-targets --all-features -- -D warnings ${{ matrix.clippy_args }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: 1.46.0
          - rust: stable
          - rust: beta
          - rust: nightly

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Install profiling tools
      if: matrix.rust == 'nightly'
      run: rustup component add llvm-tools-preview

    - name: Install grcov
      if: matrix.rust == 'nightly'
      run: cargo install grcov

    # build
    - name: cargo build with all features
      run: cargo build --workspace --verbose --all-targets --all-features

    # build no_std
    - name: cargo build protocol with no default features
      run: cargo build --manifest-path x11rb-protocol/Cargo.toml --no-default-features --features=all-extensions

    - name: Add rustflag for instrument coverage
      if: matrix.rust == 'nightly'
      run: echo "RUSTFLAGS=-C instrument-coverage" >> $GITHUB_ENV

    # test
    - name: cargo test with all features
      run: cargo test --workspace --verbose --all-features
      env:
        LLVM_PROFILE_FILE: coverage-%m.profraw

    # doc
    - name: cargo doc with all features
      run: cargo doc --workspace --verbose --all-features

    # run examples
    - name: Prepare run examples
      run: |
          echo '#!/bin/bash
              cd x11rb || exit 1
              for example in examples/*.rs; do
                  example=${example/examples\//}
                  example=${example/.rs/}
                  if [ "$example" != tutorial ] ; then
                      X11RB_EXAMPLE_TIMEOUT=1 xvfb-run -a cargo run --example "$example" "$@" || exit 1
                  fi
              done
          ' > run_examples && chmod a+x run_examples
    - name: run examples with RustConnection
      run: ./run_examples --features "$MOST_FEATURES libc"
    - name: run examples with XCBConnection
      run: ./run_examples --features "$MOST_FEATURES libc allow-unsafe-code"
    - name: run examples with XCBConnection and dl-libxcb
      run: ./run_examples --features "$MOST_FEATURES libc allow-unsafe-code dl-libxcb"

    # run code generator in nightly builds for coverage
    - name: Run code generator
      if: matrix.rust == 'nightly'
      run: make
      env:
        LLVM_PROFILE_FILE: coverage-%m.profraw

    - name: Prepare coverage information for upload
      if: matrix.rust == 'nightly'
      run: grcov $(find ./ -type f -name "coverage-*.profraw") -s . --binary-path ./target/debug --branch --ignore-not-existing --ignore 'tests/*' -t coveralls+ --token ? -o ./coveralls.json
    - name: Upload to codecov.io
      if: matrix.rust == 'nightly'
      uses: codecov/codecov-action@v2
      with:
        files: ./coveralls.json
        flags: tests
        verbose: true
      continue-on-error: true

  big-endian-test:
    runs-on: ubuntu-latest
    env:
      CROSS_TARGET: mips64-unknown-linux-gnuabi64
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install cross rust
      run: rustup target add "$CROSS_TARGET"
    - name: Install cross
      run: cargo install cross --force
    - name: cargo test
      run: cross test --target "$CROSS_TARGET" --verbose --package x11rb --features "$MOST_FEATURES"

  # future-proof against issue #721
  non-linux-unix-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Run tests
      run: cargo test --verbose --package x11rb --features "$MOST_FEATURES"
